# Generated by Django 5.1.3 on 2026-04-07 13:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компанія')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адреса')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактна особа')),
                ('purpose', models.CharField(blank=True, max_length=300, verbose_name='Призначення апарату')),
                ('hot_medium', models.CharField(blank=True, max_length=100, verbose_name='Гар: середовище')),
                ('hot_temp_in', models.CharField(blank=True, max_length=20, verbose_name='Гар: t° вхід (°C)')),
                ('hot_temp_out', models.CharField(blank=True, max_length=20, verbose_name='Гар: t° вихід (°C)')),
                ('hot_flow_in', models.CharField(blank=True, max_length=20, verbose_name='Гар: витрата вхід')),
                ('hot_flow_out', models.CharField(blank=True, max_length=20, verbose_name='Гар: витрата вихід')),
                ('hot_pressure_in', models.CharField(blank=True, max_length=20, verbose_name='Гар: тиск вхід')),
                ('hot_pressure_out', models.CharField(blank=True, max_length=20, verbose_name='Гар: тиск вихід')),
                ('hot_pressure_drop', models.CharField(blank=True, max_length=20, verbose_name='Гар: допуст. Δp (кПа)')),
                ('cold_medium', models.CharField(blank=True, max_length=100, verbose_name='Хол: середовище')),
                ('cold_temp_in', models.CharField(blank=True, max_length=20, verbose_name='Хол: t° вхід (°C)')),
                ('cold_temp_out', models.CharField(blank=True, max_length=20, verbose_name='Хол: t° вихід (°C)')),
                ('cold_flow_in', models.CharField(blank=True, max_length=20, verbose_name='Хол: витрата вхід')),
                ('cold_flow_out', models.CharField(blank=True, max_length=20, verbose_name='Хол: витрата вихід')),
                ('cold_pressure_in', models.CharField(blank=True, max_length=20, verbose_name='Хол: тиск вхід')),
                ('cold_pressure_out', models.CharField(blank=True, max_length=20, verbose_name='Хол: тиск вихід')),
                ('cold_pressure_drop', models.CharField(blank=True, max_length=20, verbose_name='Хол: допуст. Δp (кПа)')),
                ('heat_load', models.CharField(blank=True, max_length=20, verbose_name='Теплове навантаження (кВт)')),
                ('hot_thermo_temp', models.CharField(blank=True, max_length=20, verbose_name='Гар: t° теплофіз.')),
                ('hot_density', models.CharField(blank=True, max_length=20, verbose_name='Гар: густина кг/м³')),
                ('hot_specific_heat', models.CharField(blank=True, max_length=20, verbose_name='Гар: теплоємн. Дж/кг·K')),
                ('hot_conductivity', models.CharField(blank=True, max_length=20, verbose_name='Гар: теплопров. Вт/м·K')),
                ('hot_viscosity', models.CharField(blank=True, max_length=20, verbose_name="Гар: в'язкість сПз")),
                ('cold_thermo_temp', models.CharField(blank=True, max_length=20, verbose_name='Хол: t° теплофіз.')),
                ('cold_density', models.CharField(blank=True, max_length=20, verbose_name='Хол: густина кг/м³')),
                ('cold_specific_heat', models.CharField(blank=True, max_length=20, verbose_name='Хол: теплоємн. Дж/кг·K')),
                ('cold_conductivity', models.CharField(blank=True, max_length=20, verbose_name='Хол: теплопров. Вт/м·K')),
                ('cold_viscosity', models.CharField(blank=True, max_length=20, verbose_name="Хол: в'язкість сПз")),
                ('plate_material', models.CharField(blank=True, max_length=100, verbose_name='Матеріал пластин')),
                ('plate_material_unit', models.CharField(blank=True, max_length=20, verbose_name='Розмір пластин (мм)')),
                ('connection_type', models.CharField(blank=True, max_length=100, verbose_name="Тип під'єднань")),
                ('design_pressure', models.CharField(blank=True, max_length=20, verbose_name='Розр. тиск (бар)')),
                ('flanges', models.CharField(blank=True, max_length=100, verbose_name='Зворотні фланці')),
                ('flanges_count', models.CharField(blank=True, max_length=20, verbose_name='К-ть фланців (шт.)')),
                ('comments', models.TextField(blank=True, verbose_name='Коментарі')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'Опрацьовується'), ('responded', 'Відповідь надана'), ('closed', 'Закрито')], default='new', max_length=20, verbose_name='Статус')),
                ('internal_notes', models.TextField(blank=True, help_text='Нотатки для команди — не видимі замовнику', verbose_name='Внутрішні примітки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адреса')),
                ('language', models.CharField(blank=True, default='uk', max_length=10, verbose_name='Мова')),
                ('source_page', models.CharField(blank=True, max_length=500, verbose_name='Сторінка-джерело')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачі')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Опитувальний лист',
                'verbose_name_plural': 'Опитувальні листи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='leads_surve_status_3383b9_idx'), models.Index(fields=['email'], name='leads_surve_email_21d194_idx'), models.Index(fields=['created_at'], name='leads_surve_created_87d39f_idx')],
            },
        ),
    ]
